# fly.toml file generated for polished-field-1822 on 2022-12-01T22:52:05+01:00

app = "polished-field-1822"
kill_signal = "SIGINT"
kill_timeout = 5
# processes = []

[build]
  dockerfile = "Dockerfile"

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 4000
#  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 80
